# coding: utf-8
CategoryGeneralMapDic = {
                    "AnzhItem":{u"应用程序":"App", 
                                u"游戏":"Game"}}

CategoryDetailMapDic = {
                    "ITunesItem": {
                        u'图书': 'Books',
                        u'商业': 'Business',
                        u'商品指南': 'Catalogs',
                        u'教育': "Education",
                        u'娱乐': "Entertainment",
                        u'财务': "Finance",
                        u'美食佳饮': "Food & Drink",
                        u'健康健美': "Health & Fitness",
                        u'生活': "Lifestyle",
                        u'医疗': "Medical",
                        u'音乐': "Music",
                        u'导航': "Navigation",
                        u'新闻': "News",
                        u'报刊杂志': "Newsstand",
                        u'摄影与录像': "Photo & Video",
                        u'效率': "Productivity",
                        u'参考': 'Reference',
                        u'社交': "Social Networking",
                        u'体育': "Sports",
                        u'旅行': "Travel",
                        u'工具': "Utilities",
                        u'天气': "Weather",
                        u'游戏': "Games",
                        u'动作游戏': "Action",
                        u'探险游戏': "Adventure",
                        u'街机游戏': "Arcade",
                        u'桌面游戏': "Board",
                        u'扑克牌游戏': "Card",
                        u'娱乐场游戏': "Casino",
                        u'骰子游戏': "Dice",
                        u'教育游戏': "Educational",
                        u'家庭游戏': "Family",
                        u'儿童游戏': "Kids",
                        u'音乐': "Music",
                        u'智力游戏': "Puzzle",
                        u'赛车游戏': "Racing",
                        u'角色扮演游戏': "Role Playing",
                        u'模拟游戏': "Simulation",
                        u'策略游戏': "Strategy",
                        u'小游戏': "Trivia",
                        u'文字游戏': "Word",
                    },
                    "WanDouJiaItem":{
                        u"全部应用": "App",
                        u"应用": "App",
                        u"系统工具":"Tools",
                        u"社交":"Social",
                        u"音乐视频": "Media",
                        #TODO 也可以是Communication
                        u"浏览器·输入法": "Tools",
                        u"交通地图": "Transportation",
                        u"购物娱乐": "Shopping",
                        u"阅读资讯": "News",
                        u"拍照": "Photography",
                        u"词典": "Productivity",
                        u"主题桌面": "Wallpaper",
                        u"健康": "Health",                       
                        u"通信": "Communication",
                        u"办公": "Productivity",
                        u"理财": "Finance",
                        u"其它": "Others",
                        u"游戏": "Game",
                        u"全部游戏": "Game",
                        u"休闲益智": "Casual",
                        u"动作竞技": "Casual",
                        u"体育竞速": "Racing",
                        u"角色扮演": "Arcade",
                        u"经营策略": "Casual",
                        u"射击冒险": "Arcade",
                        u"网络模拟": "Casual"
                    },

                    "NduoaItem": {
                        u"软件": "App",
                        u"全部软件": "App",
                        #TODO
                        u"必备软件": "Tools",
                        u"社交通讯": "Communication",
                        u"影音拍摄": "Media",
                        u"办公理财": "Productivity",
                        u"新闻资讯": "News",
                        u"地图导航": "Transportation",
                        u"系统工具": "Tools",
                        u"生活购物旅行": "Shopping",
                        u"壁纸主题铃声": "Wallpaper",
                        u"漫画电子书": "Books",
                        u"DIY作品": "Others",
                        u"游戏": "Game",
                        u"全部游戏": "Game",
                        #TODO
                        u"必备游戏": "Game",
                        u"动作冒险": "Arcade",
                        u"角色扮演": "Arcade",
                        u"飞行射击": "Arcade",
                        u"棋牌休闲": "Casual",
                        u"经营策略": "Casual",
                        u"体育竞技": "Racing",
                        u"网络游戏": "Casual",
                        u"模拟游戏": "Arcade",
                    },

                    "AnzhItem":{u"应用程序":"App",
                                u"系统工具":"Tools",
                                u"手机安全":"Tools",
                                u"浏览器":"Communication",
                                u"输入法":"Tools",
                                u"音乐音频":"Music",
                                u"主题桌面":"Wallpaper",
                                u"视频播放":"Media",
                                u"摄影美化":"Photography",
                                u"气象交通":"Weather",
                                u"购物支付":"Shopping",
                                u"金融理财":"Finance",
                                u"通信聊天":"Communication",
                                u"综合服务":"Lifestyle",
                                u"社交网络":"Social",
                                u"新闻阅读":"News",
                                u"办公学习":"Productivity",
                                u"电子图书":"Books",
                                u"创意休闲":"Casual",
                                u"动作射击":"Arcade",
                                u"益智棋牌":"Cards",
                                u"角色扮演":"Casual",
                                u"体育竞速":"Racing",
                                u"网络游戏":"Casual",
                                u"模拟游戏":"Arcade",
                                u"策略经营":"Casual",
                                u"竞技飞行":"Casual"
                            },
                      
                    "AppchItem":{
                                u"输入法软件下载":"Tools",
                                u"浏览器软件下载":"Tools",
                                u"动态壁纸软件下载":"Wallpaper",
                                u"系统工具软件下载":"Tools",
                                u"便捷生活软件下载":"Lifestyle",
                                u"影音播放软件下载":"Media",
                                u"通话通讯软件下载":"Communication",
                                u"社交网络软件下载":"Social",
                                u"主题插件软件下载":"Personalization",
                                u"拍摄美化软件下载":"Photography",
                                u"新闻资讯软件下载":"News",
                                u"图书阅读软件下载":"Books",
                                u"学习办公软件下载":"Productivity",
                                u"网购支付软件下载":"Shopping",
                                u"金融理财软件下载":"Finance",
                                u"输入法":"Tools",
                                u"浏览器":"Tools",
                                u"动态壁纸":"Wallpaper",
                                u"系统工具":"Tools",
                                u"便捷生活":"Lifestyle",
                                u"影音播放":"Media",
                                u"通话通讯":"Communication",
                                u"社交网络":"Social",
                                u"主题插件":"Personalization",
                                u"拍摄美化":"Photography",
                                u"新闻资讯":"News",
                                u"图书阅读":"Books",
                                u"学习办公":"Productivity",
                                u"网购支付":"Shopping",
                                u"金融理财":"Finance",
                                u"动作竞技":"Arcade",
                                u"策略游戏":"Casual",
                                u"角色养成":"Casual",                                       
                                u"射击游戏":"Arcade",                                       
                                u"体育赛车":"Racing",                                       
                                u"益智棋牌":"Cards",                                       
                                u"模拟辅助":"Casual"
                            }, 

                   "HiApkItem":{u"所有应用":"App",
                                u"所有游戏":"Game",
                                u"通讯.聊天":"Communication",
                                u"网络.社区":"Social",
                                u"影音.图像":"Media",
                                u"办公.财经":"Productivity",
                                u"资讯.词典":"News",
                                u"旅行.地图":"Travel",
                                u"输入法.系统工具":"Tools",
                                u"生活.购物":"Shopping",
                                u"美化.壁纸":"Wallpaper",
                                u"阅读.图书":"Books",
                                u"其他":"Others",
                                u"动作冒险":"Arcade",
                                u"角色扮演":"Arcade",
                                u"射击飞行":"Casual",
                                u"赛车竞速":"Racing",
                                u"策略经营":"Casual",
                                u"棋牌休闲":"Cards"
                            },
                        
                   "AndrmarketItem":{
                                u"热门免费个性化":"Personalization",
                                u"热门免费交通":"Transportation",
                                u"热门免费体育":"Sports",
                                u"热门免费保健与健身":"Health",
                                u"热门免费公司":"Business",
                                u"热门免费动态壁纸":"Wallpaper",
                                u"热门免费动漫":"Comics",
                                u"热门免费医药":"Medical",
                                u"热门免费图书与工具书":"Books",
                                u"热门免费天气":"Weather",
                                u"热门免费娱乐":"Entertainment",
                                u"热门免费媒体与视频":"Media",
                                u"热门免费工具":"Tools",
                                u"热门免费摄影":"Photography",
                                u"热门免费效率":"Productivity",
                                u"热门免费教育":"Education",
                                u"热门免费新闻杂志":"News",
                                u"热门免费旅游与本地出行":"Travel",
                                u"热门免费生活方式":"Lifestyle",
                                u"热门免费社交":"Social",
                                u"热门免费财经":"Finance",
                                u"热门免费购物":"Shopping",
                                u"热门免费软件与演示":"Libraries",
                                u"热门免费通信":"Communication",
                                u"热门免费音乐与音频":"Music", 
                                u"个性化":"Personalization",
                                u"交通":"Transportation",
                                u"体育":"Sports",
                                u"保健与健身":"Health",
                                u"公司":"Business",
                                u"动态壁纸":"Wallpaper",
                                u"动漫":"Comics",
                                u"医药":"Medical",
                                u"图书与工具书":"Books",
                                u"天气":"Weather",
                                u"娱乐":"Entertainment",
                                u"媒体与视频":"Media",
                                u"工具":"Tools",
                                u"摄影":"Photography",
                                u"效率":"Productivity",
                                u"教育":"Education",
                                u"新闻杂志":"News",
                                u"旅游与本地出行":"Travel",
                                u"生活方式":"Lifestyle",
                                u"社交":"Social",
                                u"窗口小部件":"Widgets",
                                u"财经":"Finance",
                                u"购物":"Shopping",
                                u"软件与演示":"Libraries",
                                u"通信":"Communication",
                                u"音乐与音频":"Music", 
                                u"游戏":"Arcade",
                                u"益智类游戏":"Brain",
                                u"纸牌游戏":"Cards",
                                u"休闲游戏":"Casual",
                                u"动态壁纸":"Wallpaper",
                                u"比赛":"Racing",
                                u"体育游戏":"Sports",
                                u"热门免费游戏":"Arcade",
                                u"热门免费益智类游戏":"Brain",
                                u"热门免费纸牌游戏":"Cards",
                                u"热门免费休闲游戏":"Casual",
                                u"热门免费动态壁纸":"Wallpaper",
                                u"热门免费比赛":"Racing",
                                u"热门免费体育游戏":"Sports",
                                u"热门免费窗口小部件":"Widgets",
                                u"Personalization":"Personalization",
                                u"Transportation":"Transportation",
                                u"Sports":"Sports",
                                u"Health & Fitness":"Health",
                                u"Business":"Business",
                                u"Live Wallpaper":"Wallpaper",
                                u"Comics":"Comics",
                                u"Medical":"Medical",
                                u"Books & Reference":"Books",
                                u"Weather":"Weather",
                                u"Entertainment":"Entertainment",
                                u"Media & Video":"Media",
                                u"Tools":"Tools",
                                u"Photography":"Photography",
                                u"Productivity":"Productivity",
                                u"Education":"Education",
                                u"News & Magazines":"News",
                                u"Travel & Local":"Travel",
                                u"Lifestyle":"Lifestyle",
                                u"Social":"Social",
                                u"Widgets":"Widgets",
                                u"Finance":"Finance",
                                u"Shopping":"Shopping",
                                u"Libraries & Demo":"Libraries",
                                u"Communication":"Communication",
                                u"Music & Audio":"Music",
                                u"Arcade & Action":"Arcade",
                                u"Brain & Puzzle":"Brain",
                                u"Cards & Casino":"Cards",
                                u"Casual":"Casual",
                                u"Racing":"Racing",
                                u"Sports Games":"Sports",
                                u"Top Free in Arcade & Action":"Arcade",
                                u"Top Free in Brain & Puzzle":"Brain",
                                u"Top Free in Cards & Casino":"Cards",
                                u"Top Free in Casual":"Casual",
                                u"Top Free in Live Wallpaper":"Wallpaper",
                                u"Top Free in Racing":"Racing",
                                u"Top Free in Sports Games":"Sports",
                                u"Top Free in Widgets":"Widgets",
                                u"Top Free in Personalization":"Personalization",
                                u"Top Free in Transportation":"Transportation",
                                u"Top Free in Sports":"Sports",
                                u"Top Free in Health & Fitness":"Health",
                                u"Top Free in Business":"Business",
                                u"Top Free in Comics":"Comics",
                                u"Top Free in Medical":"Medical",
                                u"Top Free in Books & Reference":"Books",
                                u"Top Free in Weather":"Weather",
                                u"Top Free in Entertainment":"Entertainment",
                                u"Top Free in Media & Video":"Media",
                                u"Top Free in Tools":"Tools",
                                u"Top Free in Photography":"Photography",
                                u"Top Free in Productivity":"Productivity",
                                u"Top Free in Education":"Education",
                                u"Top Free in News & Magazines":"News",
                                u"Top Free in Travel & Local":"Travel",
                                u"Top Free in Lifestyle":"Lifestyle",
                                u"Top Free in Social":"Social",
                                u"Top Free in Personalization":"Personalization",
                                u"Top Free in Transportation":"Transportation",
                                u"Top Free in Sports":"Sports",
                                u"Top Free in Health & Fitness":"Health",
                                u"Top Free in Business":"Business",
                                u"Top Free in Comics":"Comics",
                                u"Top Free in Medical":"Medical",
                                u"Top Free in Books & Reference":"Books",
                                u"Top Free in Weather":"Weather",
                                u"Top Free in Entertainment":"Entertainment",
                                u"Top Free in Media & Video":"Media",
                                u"Top Free in Tools":"Tools",
                                u"Top Free in Photography":"Photography",
                                u"Top Free in Productivity":"Productivity",
                                u"Top Free in Education":"Education",
                                u"Top Free in News & Magazines":"News",
                                u"Top Free in Travel & Local":"Travel",
                                u"Top Free in Lifestyle":"Lifestyle",
                                u"Top Free in Social":"Social",
                                u"Top Free in Finance":"Finance",
                                u"Top Free in Shopping":"Shopping",
                                u"Top Free in Libraries & Demo":"Libraries",
                                u"Top Free in Communication":"Communication",
                                u"Top Free in Music & Audio":"Music", 
                                u"Top Free in Finance":"Finance",
                                u"Top Free in Shopping":"Shopping",
                                u"Top Free in Libraries & Demo":"Libraries",
                                u"Top Free in Communication":"Communication",
                                u"Top Free in Music & Audio":"Music" 
                            } 


                  }

